<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SJPC" failures="1" tests="1" name="TestRunner.TestRunner" time="23.283" errors="0" timestamp="2023-03-11T03:14:16 GMT" skipped="0">
  <testcase classname="TestRunner.TestRunner" name="runScenario" time="23.283">
    <failure message="expected [https://smartbazaar.co.uk/] but found [https://www.smartbazaar.co.uk/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://smartbazaar.co.uk/] but found [https://www.smartbazaar.co.uk/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at StepDefinition.TestCase.user_verifies_the_title_of_the_application(TestCase.java:25)
at âœ½.User verifies the title of the application(file:///C:/Users/charu/IdeaProjects/org.smartbazaar.com/src/test/resources/Feature/TestCase.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- TestRunner.TestRunner -->
